# Generated by Django 3.0.4 on 2020-03-17 07:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wholeseller', '0004_wbucket_wri'),
        ('manufacturer', '0003_mornament'),
    ]

    operations = [
        migrations.CreateModel(
            name='MWI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('rejected', models.DateTimeField(blank=True, null=True)),
                ('viewed', models.DateTimeField(blank=True, null=True)),
                ('Manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Manufacturer', to='manufacturer.Manufacturer')),
                ('Wholeseller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Wholeseller', to='wholeseller.Wholeseller')),
            ],
        ),
        migrations.CreateModel(
            name='Mbucket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FROM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufacturer.Manufacturer')),
                ('ORNAMENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufacturer.MOrnament')),
            ],
        ),
    ]
