# Generated by Django 3.0.4 on 2020-03-17 07:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('retailer', '0004_rbucket'),
        ('wholeseller', '0003_wornament'),
    ]

    operations = [
        migrations.CreateModel(
            name='WRI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('rejected', models.DateTimeField(blank=True, null=True)),
                ('viewed', models.DateTimeField(blank=True, null=True)),
                ('Wholeseller1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Wholeseller1', to='wholeseller.Wholeseller')),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retailer', to='retailer.retailer')),
            ],
        ),
        migrations.CreateModel(
            name='Wbucket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FROM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wholeseller.Wholeseller')),
                ('ORNAMENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wholeseller.WOrnament')),
            ],
        ),
    ]
