# Generated by Django 3.0.4 on 2020-03-17 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retailer', '0003_rornament'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rbucket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FROM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retailer.retailer')),
                ('ORNAMENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retailer.ROrnament')),
            ],
        ),
    ]
